version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: vguzelik/infra_frontend
    volumes:
      - ../frontend/:/app/result_build/


  backend:
    image: vguzelik/infra_backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
      - frontend
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend



volumes:
  postgres_data:
  static_value:
  media_value:
