# Generated by Django 4.2.1 on 2023-05-11 10:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_shoppingcard_delete_shoppinglist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCard',
            new_name='ShoppingCart',
        ),
    ]
