# Generated by Django 4.2.1 on 2023-05-13 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_tag_color_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator('^#[A-Fa-f0-9]{6}$')]),
        ),
    ]
